# Generated by Django 3.0.7 on 2020-06-26 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='photo_1',
            field=models.ImageField(blank=True, upload_to='photos/listings/%Y-%m-%d/'),
        ),
        migrations.AlterField(
            model_name='property',
            name='photo_2',
            field=models.ImageField(blank=True, upload_to='photos/listings/%Y-%m-%d/'),
        ),
        migrations.AlterField(
            model_name='property',
            name='photo_3',
            field=models.ImageField(blank=True, upload_to='photos/listings/%Y-%m-%d/'),
        ),
        migrations.AlterField(
            model_name='property',
            name='photo_4',
            field=models.ImageField(blank=True, upload_to='photos/listings/%Y-%m-%d/'),
        ),
        migrations.AlterField(
            model_name='property',
            name='photo_5',
            field=models.ImageField(blank=True, upload_to='photos/listings/%Y-%m-%d/'),
        ),
        migrations.AlterField(
            model_name='property',
            name='photo_6',
            field=models.ImageField(blank=True, upload_to='photos/listings/%Y-%m-%d/'),
        ),
        migrations.AlterField(
            model_name='property',
            name='thumb_nail',
            field=models.ImageField(upload_to='photos/listings/%Y-%m-%d/'),
        ),
        migrations.AlterField(
            model_name='realtor',
            name='photo',
            field=models.ImageField(upload_to='photos/realtor/%Y-%m-%d/'),
        ),
    ]
