# Generated by Django 3.0.7 on 2020-06-27 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0002_auto_20200627_1323'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteConfiguration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='YourSiteName', max_length=50)),
                ('phone', models.CharField(default='YourPhoneNumber', max_length=20)),
                ('email', models.EmailField(default='YourEmailName', max_length=50)),
            ],
            options={
                'verbose_name': 'Site Configuration',
            },
        ),
    ]
